name: Update Server Version

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  test:
    runs-on: runner_pool
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: npm version patch
