name: Update Server Version

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Complete git config"
          npm version patch
          git push
