name: npm-version-update

on:
  push:
    branches:
      - main

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{secrets.FULL_PERMISSIONS_TOKEN}}

      - name: Run version update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Complete git config"
          npm run testScript

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
