name: Post commit

on:
  push:
    branches:
      - main

jobs:
  post-commit:
    if: env.GITHUB_HEAD_REF == 'staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Complete git config"
          echo $GITHUB_HEAD_REF
          npm version patch
          git push
