# on:
#   push:
#     branches: [master]

# jobs:
#   post-commit:
#     if: ${{(github.event.push.base.ref == 'main') && (github.event.push.head.ref == 'staging')}}
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           token: ${{secrets.FULL_PERMISSIONS_SECRET}}

#       - name: Use Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "14.x"

#       - run: |
#           git config user.name github-actions
#           git config user.email github-actions@github.com
#           git fetch
#           git checkout staging
#           npm version patch
#           git push

# name: Increment API version

on:
  pull_request:
    types: [closed]

jobs:
  increment-api-version:
    if: ${{ (github.event.pull_request.merged) && (github.event.pull_request.base.ref == 'main') && (github.event.pull_request.head.ref == 'staging')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.FULL_PERMISSIONS_SECRET }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout staging
          ls -a
          npm version patch
          git push
        working-directory: data

name: Increment API version
